CREATE TABLE `quant`.`order` (
  `order_id` BIGINT NOT NULL,
  `symbol` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `client_order_id` VARCHAR(45) NULL,
  `price` DOUBLE NULL,
  `avg_price` DOUBLE NULL,
  `origqty` DOUBLE NULL,
  `time_in_force` VARCHAR(45) NULL,
  `order_type` VARCHAR(45) NULL,
  `reduce_only` TINYINT NULL,
  `close_position` TINYINT NULL,
  `side` VARCHAR(45) NULL,
  `position_side` VARCHAR(45) NULL,
  `stop_price` DOUBLE NULL,
  `working_type` VARCHAR(45) NULL,
  `price_protect` TINYINT NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`order_id`));